In [69]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Polygon

In [63]:
# Load the district data
districts = gpd.read_file('madrid_distrito_polygons.geojson')

In [64]:
# Load the postcode data
postcodes = gpd.read_file('Carto_postal_codes.geojson')

In [65]:
# Filter postcodes for Madrid
postcodes = postcodes[postcodes['COD_POSTAL'].str.startswith('280')]

In [ ]:
#makingsomechangetocheckgit

In [66]:
# Create a list to store all the overlap data
overlap_data = []

In [47]:
districts

,CUDIS,geometry,top_postcode,top_postcode_percentage,second_postcode,second_postcode_percentage,total_percentage
0,2807901,"POLYGON ((-3.71116 40.40653, -3.71161 40.40667...",,0,,0,0
1,2807902,"POLYGON ((-3.70657 40.39560, -3.70728 40.39584...",,0,,0,0
2,2807903,"POLYGON ((-3.67902 40.40098, -3.67915 40.40100...",,0,,0,0
3,2807904,"POLYGON ((-3.67966 40.42169, -3.67985 40.42167...",,0,,0,0
4,2807905,"POLYGON ((-3.67929 40.43747, -3.67930 40.43747...",,0,,0,0
5,2807906,"POLYGON ((-3.70504 40.44691, -3.70606 40.44696...",,0,,0,0
6,2807907,"POLYGON ((-3.71214 40.43022, -3.71257 40.43026...",,0,,0,0
7,2807908,"POLYGON ((-3.72113 40.47115, -3.72172 40.47129...",,0,,0,0
8,2807909,"POLYGON ((-3.72243 40.41706, -3.72248 40.41704...",,0,,0,0
9,2807910,"POLYGON ((-3.76683 40.36396, -3.76806 40.36287...",,0,,0,0
10,2807911,"POLYGON ((-3.76152 40.35794, -3.76269 40.35814...",,0,,0,0
11,2807912,"POLYGON ((-3.71420 40.36439, -3.71778 40.36475...",,0,,0,0
12,2807913,"POLYGON ((-3.65265 40.37597, -3.65278 40.37577...",,0,,0,0
13,2807914,"POLYGON ((-3.65170 40.40268, -3.65183 40.40279...",,0,,0,0
14,2807915,"POLYGON ((-3.65933 40.42316, -3.65938 40.42343...",,0,,0,0
15,2807916,"POLYGON ((-3.65588 40.45892, -3.65628 40.45940...",,0,,0,0
16,2807917,"POLYGON ((-3.72335 40.33331, -3.72367 40.33355...",,0,,0,0
17,2807918,"POLYGON ((-3.64197 40.32870, -3.64203 40.32873...",,0,,0,0
18,2807919,"POLYGON ((-3.61989 40.39035, -3.62153 40.39071...",,0,,0,0
19,2807920,"POLYGON ((-3.62493 40.41973, -3.62540 40.42041...",,0,,0,0
20,2807921,"POLYGON ((-3.59503 40.45005, -3.59565 40.45007...",,0,,0,0

In [48]:
postcodes

,ID_CP,COD_POSTAL,ALTA_DB,CODIGO_INE,geometry
68,280790000026,28008,2015-07-09,28079,"MULTIPOLYGON (((-3.71876 40.43541, -3.71885 40..."
69,280790000001,28053,2015-07-09,28079,"MULTIPOLYGON (((-3.66055 40.39356, -3.66069 40..."
70,280790000002,28041,2015-07-09,28079,"MULTIPOLYGON (((-3.68934 40.38186, -3.68872 40..."
71,280790000003,28036,2015-07-09,28079,"MULTIPOLYGON (((-3.67148 40.47061, -3.67256 40..."
72,280790000004,28033,2015-07-09,28079,"MULTIPOLYGON (((-3.64112 40.48052, -3.63943 40..."
73,280790000005,28043,2015-07-09,28079,"MULTIPOLYGON (((-3.62662 40.46796, -3.62560 40..."
74,280790000006,28045,2015-07-09,28079,"MULTIPOLYGON (((-3.67317 40.39462, -3.67357 40..."
75,280790000009,28044,2015-07-09,28079,"MULTIPOLYGON (((-3.76073 40.37202, -3.76056 40..."
76,280790000010,28039,2015-07-09,28079,"MULTIPOLYGON (((-3.69588 40.46433, -3.69648 40..."
77,280790000007,28048,2015-07-09,28079,"MULTIPOLYGON (((-3.71498 40.58269, -3.71358 40..."
78,280790000027,28009,2015-07-09,28079,"MULTIPOLYGON (((-3.66911 40.42142, -3.66912 40..."
79,280790000008,28047,2015-07-09,28079,"MULTIPOLYGON (((-3.72643 40.40390, -3.72823 40..."
80,280790000011,28040,2015-07-09,28079,"MULTIPOLYGON (((-3.71934 40.45947, -3.71935 40..."
81,280790000012,28035,2015-07-09,28079,"MULTIPOLYGON (((-3.71974 40.50011, -3.72245 40..."
82,280790000028,28010,2015-07-09,28079,"MULTIPOLYGON (((-3.69136 40.43789, -3.69091 40..."
83,280790000018,28054,2015-07-09,28079,"MULTIPOLYGON (((-3.78391 40.37816, -3.78405 40..."
84,280790000013,28034,2015-07-09,28079,"MULTIPOLYGON (((-3.67405 40.48408, -3.67749 40..."
85,280790000014,28042,2015-07-09,28079,"MULTIPOLYGON (((-3.55426 40.51133, -3.55443 40..."
86,280790000015,28055,2015-07-09,28079,"MULTIPOLYGON (((-3.65558 40.51297, -3.65531 40..."
87,280790000016,28050,2015-07-09,28079,"MULTIPOLYGON (((-3.65794 40.51145, -3.65801 40..."
88,280790000017,28049,2015-07-09,28079,"MULTIPOLYGON (((-3.64591 40.63918, -3.64454 40..."
89,280790000023,28005,2015-07-09,28079,"MULTIPOLYGON (((-3.71483 40.41409, -3.71380 40..."
90,280790000033,28015,2015-07-09,28079,"MULTIPOLYGON (((-3.71529 40.43890, -3.71402 40..."
91,280790000034,28016,2015-07-09,28079,"MULTIPOLYGON (((-3.66495 40.46010, -3.66477 40..."
92,280790000035,28017,2015-07-09,28079,"MULTIPOLYGON (((-3.62477 40.41875, -3.62412 40..."
93,280790000036,28018,2015-07-09,28079,"MULTIPOLYGON (((-3.65897 40.39272, -3.65843 40..."
94,280790000037,28019,2015-07-09,28079,"MULTIPOLYGON (((-3.72273 40.40455, -3.72265 40..."
95,280790000038,28020,2015-07-09,28079,"MULTIPOLYGON (((-3.69300 40.44935, -3.69339 40..."
96,280790000021,28003,2015-07-09,28079,"MULTIPOLYGON (((-3.70757 40.44731, -3.70688 40..."
97,280790000022,28004,2015-07-09,28079,"MULTIPOLYGON (((-3.69146 40.42578, -3.69155 40..."
98,280790000019,28001,2015-07-09,28079,"MULTIPOLYGON (((-3.68032 40.42962, -3.67953 40..."
99,280790000020,28002,2015-07-09,28079,"MULTIPOLYGON (((-3.66301 40.45222, -3.66278 40..."
100,280790000024,28006,2015-07-09,28079,"MULTIPOLYGON (((-3.67760 40.43726, -3.67746 40..."
101,280790000025,28007,2015-07-09,28079,"MULTIPOLYGON (((-3.66911 40.42142, -3.66856 40..."
102,280790000029,28011,2015-07-09,28079,"MULTIPOLYGON (((-3.73887 40.43409, -3.73861 40..."
103,280790000030,28012,2015-07-09,28079,"MULTIPOLYGON (((-3.70232 40.41664, -3.70207 40..."
104,280790000031,28014,2015-07-09,28079,"MULTIPOLYGON (((-3.68841 40.41933, -3.68852 40..."
105,280790000032,28013,2015-07-09,28079,"MULTIPOLYGON (((-3.70778 40.42166, -3.70682 40..."
106,280790000039,28021,2015-07-09,28079,"MULTIPOLYGON (((-3.70664 40.35066, -3.70577 40..."
107,280790000041,28025,2015-07-09,28079,"MULTIPOLYGON (((-3.71751 40.38512, -3.71772 40..."
108,280790000042,28026,2015-07-09,28079,"MULTIPOLYGON (((-3.68934 40.38186, -3.69004 40..."
109,280790000043,28027,2015-07-09,28079,"MULTIPOLYGON (((-3.61405 40.44980, -3.61402 40..."
110,280790000046,28022,2015-07-09,28079,"MULTIPOLYGON (((-3.53549 40.44648, -3.53550 40..."
111,280790000053,28032,2015-07-09,28079,"MULTIPOLYGON (((-3.57954 40.41734, -3.58093 40..."
112,280790000040,28046,2015-07-09,28079,"MULTIPOLYGON (((-3.69067 40.44640, -3.69053 40..."
113,280790000054,28052,2015-07-09,28079,"MULTIPOLYGON (((-3.52120 40.41245, -3.52120 40..."
114,280790000044,28024,2015-07-09,28079,"MULTIPOLYGON (((-3.75566 40.39853, -3.75707 40..."
115,280790000045,28028,2015-07-09,28079,"MULTIPOLYGON (((-3.66068 40.43086, -3.66052 40..."
116,280790000047,28023,2015-07-09,28079,"MULTIPOLYGON (((-3.79457 40.45578, -3.79487 40..."
117,280790000055,28038,2015-07-09,28079,"MULTIPOLYGON (((-3.63197 40.38539, -3.63198 40..."
118,280790000048,28029,2015-07-09,28079,"MULTIPOLYGON (((-3.68635 40.48259, -3.68636 40..."
119,280790000049,28030,2015-07-09,28079,"MULTIPOLYGON (((-3.63084 40.41520, -3.62811 40..."
120,280790000050,28031,2015-07-09,28079,"MULTIPOLYGON (((-3.55450 40.37173, -3.55515 40..."
121,280790000052,28037,2015-07-09,28079,"MULTIPOLYGON (((-3.61238 40.42253, -3.61280 40..."
122,280790000051,28051,2015-07-09,28079,"MULTIPOLYGON (((-3.59833 40.37303, -3.59198 40..."

In [67]:
# Iterate through each district
for index, district in districts.iterrows():
    # Store top six postcodes and their percentage overlaps
    top_postcodes = ['']*6
    top_percentages = [0]*6
    
    # Get the area of the current district region
    district_area = district['geometry'].area
    
    # Iterate through each postcode
    for _, postcode in postcodes.iterrows():
        # Get the intersection of the current district and postcode region
        intersection = district['geometry'].intersection(postcode['geometry'])
        
        # Calculate the overlap percentage
        overlap_percentage = intersection.area / district_area * 100
        
        # Insert the postal code and its overlap percentage into the sorted lists
        for i in range(6):
            if overlap_percentage > top_percentages[i]:
                top_percentages.insert(i, overlap_percentage)
                top_postcodes.insert(i, postcode['COD_POSTAL'])
                # Keep only the top six
                top_percentages = top_percentages[:6]
                top_postcodes = top_postcodes[:6]
                break

    # Add the top six postcodes and their overlap percentages to the overlap data
    for i in range(6):
        overlap_data.append({
            'CUDIS': district['CUDIS'],
            'COD_POSTAL': top_postcodes[i],
            'Connection_order': i+1,
            'Percentage_overlap': top_percentages[i]
        })

C:\Users\aksha\Desktop\PythonProjects\polygons\env\lib\site-packages\shapely\set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)

In [72]:
# Convert the overlap data to a DataFrame
overlap_df = pd.DataFrame(overlap_data)

In [73]:
overlap_df

       CUDIS COD_POSTAL  Connection_order  Percentage_overlap
0    2807901      28004                 1           22.684622
1    2807901      28013                 2           19.442788
2    2807901      28012                 3           18.425787
3    2807901      28005                 4           18.131429
4    2807901      28014                 5           10.323541
..       ...        ...               ...                 ...
121  2807921      28055                 2            6.221837
122  2807921      28043                 3            0.275256
123  2807921      28022                 4            0.227291
124  2807921      28033                 5            0.005397
125  2807921                            6            0.000000

[126 rows x 4 columns]

In [75]:
# Save the DataFrame as a CSV file
overlap_df.to_csv('cudis_pcode_overlap_madrid.csv', index=False)